cargo-features = ["edition2021"]

[package]
name = "clock-it"
version = "0.1.0"
edition = "2021"

[dependencies.rand]
version = "0.8.4"

[dependencies.druid]
git = "https://github.com/linebender/druid.git"
features = [ "im" ]
